// Generated by CoffeeScript 1.7.1
(function() {
  var mailOptions, nodemailer, transporter;

  nodemailer = require('nodemailer');

  transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: '587',
    secure: false,
    ignoreTLS: false,
    debug: true,
    auth: {
      user: 'cyopticsmexico@gmail.com',
      pass: 'kerberos86'
    }
  });

  mailOptions = {
    from: 'Aldo Mendez <cyopticsmexico@gmail.com>',
    to: 'aldo.mendez@avagotech.com',
    subject: 'Hello',
    text: 'Hola Mundo',
    html: 'Hola <b>mundo</b>'
  };

  transporter.sendMail(mailOptions, function(error, info) {
    if (error) {
      return console.log(error);
    } else {
      return console.log("Message sent: " + info.response);
    }
  });

}).call(this);

//# sourceMappingURL=mainApp.map
