// Generated by CoffeeScript 1.7.1
(function() {
  var assignEmail, completeEmail, emailjs, getJSON, pendingAssign, pendingComplete, server, _;

  emailjs = require('emailjs');

  getJSON = require('get-json-plz');

  _ = require('underscore');

  server = emailjs.server.connect({
    user: 'cyopticsmexico@gmail.com',
    password: 'kerberos86',
    host: 'smtp.gmail.com',
    tls: true,
    port: 587
  });

  pendingAssign = [];

  pendingComplete = [];

  assignEmail = [];

  completeEmail = [];

  pendingComplete.push("\nMantenimientos sin completar\n=============================\n");

  getJSON('http://jupiter.avagotech.net/apps/qa/maint-dev/toolbox/toolbox.php?action=getAllPending', function(err, res) {
    var message;
    _.map(_.groupBy(res, 'MAINT_OPER'), function(el, name) {
      var supervisor, template;
      if (name === 'null') {
        pendingAssign.push("Mantenimientos sin asignar " + el.length + "\n=============================\n");
        _.map(_.groupBy(el, 'SUPERVISOR'), function(el, name) {
          var template;
          assignEmail.push(el[0].SUP_EMAIL);
          template = _.template(" <%= maint[0].SUPERVISOR %> [<%= maint.length%>]:\n <% _.each(maint, function(single) {%> <%= single.MAINT_ID %>: <%= single.E_DESC %>\n <% });%>")({
            maint: el,
            name: name
          });
          return pendingAssign.push(template);
        });
      }
      if (name !== 'null' && (el[0].EMAIL != null)) {
        completeEmail.push(el[0].EMAIL);
        supervisor = el[0].SUPERVISOR;
        template = _.template("<%= name %> [<%= maint.length%>] \n <% _.each(maint, function(single) {%><%= single.MAINT_ID %>: <%= single.E_DESC %>\n <% });%>\n")({
          maint: el,
          name: name
        });
        return pendingComplete.push(template);
      }
    });
    message = "";
    message += pendingAssign.join('\n');
    message += pendingComplete.join('\n');
    message += "Lista de correos:\n";
    message += assignEmail.join(',');
    message += '\n' + completeEmail.join(',');
    console.log(message);
    return server.send({
      from: 'MaintBot <cyopticsmexico@gmail.com>',
      to: "aldo.mendez@avagotech.com, jorge.herrera@avagotech.com",
      subject: 'Mantenimientos pendientes',
      text: "" + message
    }, function(err, message) {});
  });

}).call(this);

//# sourceMappingURL=toHerrera.map
